Member Controller 및 Service 추가
LeeHyunSeong/chatting_Jpa pull request #12
Opened 2021-06-21 18:32 UTC by LeeHyunSeong

기능 추가
- 채팅방에 친구 초대하는 기능
- 한 유저의 모든 멤버들을 구하는 기능
- 한 유저의 어떤 채팅방의 멤버를 구하는 기능
- 채팅방 접속 후 나갈 시 마지막 접속 시간 갱신 기능
- 채팅방을 나가는 기능

테스트 코드 추가

2021-06-22 12:17 UTC, woojae9488 requested changes

2021-06-22 12:17 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +        return ResponseEntity.ok(response.toString());
GetAllMemberResponse에 대한 반환값을 그대로 줘야할 거 같은데 String으로 반환값을 설정하고 toString을 한 이유가 뭐야?? 그러면 JSON 파싱도 FE에서 불가능한 거 아니야?

2021-06-22 12:17 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +public class MemberApiController {
뭔가 전체적인 흐름들이 MemberApiController을 따로 만드는 것보다 RoomApiController에 MemberService 이용해서 만드는게 좀더 효율적인 느낌이다

2021-06-22 12:17 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +        return ResponseEntity.ok(response.toString());
getMembers라는 메소드명을 보면 어떤 한 방에 대한 멤버들을 조회하는 거 같은데 실제적으로 내부 로직은 한 유저의 멤버 객체들을 가져오는 거네? 이 API가 필요한 이유가 뭐야?

2021-06-22 12:17 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +    }
HTTP GET Method에서는 대부분 Request 객체를 만들지 않고 파라미터들을 나눠서 가져가는데.. 그렇지 않은 부분도 이상하고 url path도 나였다면 `/api/rooms/{roomId}/members/{userId}` 이런 식으로 했을 거 같아.
그런데 이것도 왜 존재하는 API인지 궁금하네 이 API를 설계한 이유가 뭐야?

2021-06-22 12:17 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/service/MemberService.java
> +    }
이 메소드 하나에서만 DB를 4번 접근하는 거 같고.. 3번의 호출은 충분히 JOIN문으로 해결이 가능한 부분인 거 같은데 굳이 nativeQuery나 QueryDSL을 사용하지 않고 나눠서 호출한 이유는 뭐야??
커넥션 리소스를 낭비하지 말자

2021-06-22 12:17 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/service/MemberService.java
> +    }
이 부분 deleteById 이런 메소드를 사용할 수 있을 거 같은데..? 코딩할 때 좀 더 조사를 많이하고 충분히 생각한 이후에 PR을 보내자
프로젝트 마감 기한이 있는 것도 아니고 급하게 짤 필요가 없어

2021-06-22 15:44 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +        return ResponseEntity.ok(response.toString());
GetAllMemberResponse는 저번에 FriendApiController에서 String형태로 리턴해서 그런식으로 했는데 제가 그때 잘못 이해하고 있어가지고 다시 수정했습니다. FriendApiController는 따로 수정하겠습니다.

getMembers 메소드는 어떤 한 방에 멤버들을 조회할려고 한 게 아니라 그 카톡보면 사용자별로 채팅목록 뜨는 거 생각해서 사용자 id를 통해 멤버들을 다 읽어오는 메소드를 만들었습니다.

2021-06-22 15:48 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +public class MemberApiController {
이것도 RoomApiController 만들때 생각한 거긴 한데 멤버가 만들어지는게 채팅방을 만들때랑 채팅방에 멤버를 초대할 때인데 채팅방을 만들때 멤버가 만들어지는건 RoomApiController에서 했는데 초대하는 경우는 Room 객체가 Member 변수로 들어가긴 하지만 멤버를 만드는 기능이어서 MemberApiController에 만들었고, 나머지도 Member객체를 가져오거나 삭제하거나 변경하는거라 다 Room을 갱신하는게 아니라 Member만 갱신하는거라서 MemberApiController에 만들었습니다.

2021-06-22 15:53 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +    }
저도 맵핑 관련해서 고민하다가 저렇게 했는데 일단 MemberApiController안에서 메소드를 만들어서 /api/members/{userId}/rooms/{roomId}로 했다가, 이거는 방 정보 바꾸거나 할때 기존의 정보를 표시하거나 할 때 쓸려고 했는데 변경은 다른 메소드를 이용해서하고 이 API는 굳이 필요없는 메소드인거 같아서 삭제했습니다.

2021-06-22 15:56 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/service/MemberService.java
> +    }
일단 room객체부분에서는 db를 접근할 필요없이 hostUserMember를 사용하고, targetUser 객체부분은 pseudo 생성자를 이용해서 2번 호출로 바꿨는데, hostUserMember는 초대하는 방 정보를 알기 위해서 필요하고 마지막에 새로 초대한 Member객체를 저장하기위해서 필요한거 같습니다.

2021-06-22 15:56 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/service/MemberService.java
> +    }
이부분은 시험 끝나고 그동안 못한만큼 빨리 작업할려다가 비효율적으로 코드 짠거 같아서 수정해서 커밋했습니다...

2021-06-23 11:49 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +        return ResponseEntity.ok(response.toString());
> getMembers 메소드는 어떤 한 방에 멤버들을 조회할려고 한 게 아니라 그 카톡보면 사용자별로 채팅목록 뜨는 거 생각해서 사용자 id를 통해 멤버들을 다 읽어오는 메소드를 만들었습니다.

카톡에서 사용자 별로 채팅 목록이 뜰 때 필요한 데이터가 뭐가 있는데??
내가 생각했을 때는 채팅방 이름, 마지막 메시지, 마지막 메시지 시간, 읽지 않은 메시지 수, 채팅방 멤버들의 사진 또는 자신이 등록한 채팅방 사진 이 정도의 데이터가 필요한 거 같은데 이 데이터들을 뿌려주는 API가 과연 MemberApiController에서 처리해야하는게 맞냐를 물어보는 거였어.

2021-06-23 15:44 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +        return ResponseEntity.ok(response.toString());
> 카톡에서 사용자 별로 채팅 목록이 뜰 때 필요한 데이터가 뭐가 있는데??
내가 생각했을 때는 채팅방 이름, 마지막 메시지, 마지막 메시지 시간, 읽지 않은 메시지 수, 채팅방 멤버들의 사진 또는 자신이 등록한 채팅방 사진 이 정도의 데이터가 필요한 거 같은데 이 데이터들을 뿌려주는 API가 과연 MemberApiController에서 처리해야하는게 맞냐를 물어보는 거였어.

하나의 유저의 모든 멤버들을 가져오는 기능이니까 UserApiController로 옮기는게 맞는거 같아서 그쪽에서 호출하는 식으로 수정했습니다.

2021-06-25 10:27 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +        return ResponseEntity.ok(response.toString());
음... 내 생각은 "한 명의 유저"의 모든 "멤버"를 가져온다고 해석하는게 아니라 한 유저의 전체 "채팅방" 정보를 가져온다고 생각이 들어.
"멤버"라는 건 특정 채팅방의 인원들을 멤버라고 하지.
대부분 사람들이 카카오톡의 목록 화면을 보고 이거는 내가 채팅방에 들어가 있는 "멤버" 목록을 가져온다고 생각하지 않고 "채팅방" 목록을 가져온다고 생각하잖아

2021-06-25 10:28 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/MemberApiController.java
> +        return ResponseEntity.ok(response.toString());
그렇기 때문에 내가 아래 코멘트를 단 것들도 멤버 객체를 뽑아서 주지 말고 "채팅방 목록을 보여줄 수 있는 응답 객체"를 nativeQuery나 QueryDsl을 이용해 뽑아 반환하라고 했던거야

2021-06-30 19:11 UTC, LeeHyunSeong reviewed
Controller 및 Service 수정했습니다. nativequery 관련된 거랑 해당 코드로 테스트 코드 수정하느라 좀 걸렸습니다.

2021-07-08 11:57 UTC, woojae9488 requested changes

2021-07-08 11:57 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/RoomApiController.java
> +        List<MemberRoom> members = roomService.getMembers(userId);
왜 roomService.getMembers로 이름 지은거야?

2021-07-08 11:57 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/repository/MemberRepository.java
> +    List<MemberRoom> findAllMemberRoomByUserId(@Param("userId") Long userId);
findAllMemberRoom's'ByUserId

2021-07-08 11:57 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/repository/UserRepository.java
> +    Optional<HostNickname> findNicknameById(@Param("userId") Long userId);
findNickNameById인데 반환 객체는 HostNickname이면 이 메소드는 hostUser만 사용하는 것처럼 단정이 되는데 그것 보다는 좀 더 범용적인 반환 객체 이름이 더 나을 거 같은데

2021-07-08 11:57 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +        return hostUserName.getNickname() + ", " + roomAlias.getRoomAlias();
만약 사용자가 자신의 roomAlias를 다른 방이름으로 변경한 상태면 어떻게 해?

2021-07-08 23:30 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/model/Nickname.java
> +public interface Nickname {
Nickname.getNickname 으로 써야할텐데 조금 이상하지 않나..?

2021-07-08 23:30 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/RoomApiController.java
> +        List<MemberRoom> members = roomService.getRooms(userId);
members로 받는게 아니라 rooms로 받아야할 거 같은데

2021-07-08 23:30 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +        Nickname hostUserName = userRepository.findNicknameById(hostUserId)
Nickname이 name이랑 동일한거야?

2021-07-08 23:32 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +        List<User> users = getUsersByMemberUsers(memberUsers);
이 두 로직은 쿼리짜면 하나로 할 수 있을 거 같은데 그렇게 해보는 것도 좋지 않을까

2021-07-11 21:53 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/model/Nickname.java
> +public interface Nickname {
채팅방 친구 초대 시 채팅방 이름을 기존 멤버 나열 방식으로 변경하면서 Nickname 인터페이스는 삭제했습니다.

2021-07-11 21:53 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/controller/RoomApiController.java
> +        List<MemberRoom> members = roomService.getRooms(userId);
해당 내용은 수정했습니다.

2021-07-11 21:53 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +        Nickname hostUserName = userRepository.findNicknameById(hostUserId)
채팅방 친구 초대 시 채팅방 이름을 기존 멤버 나열 방식으로 변경하면서 Nickname 인터페이스는 삭제했습니다.

2021-07-11 21:56 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +        List<User> users = getUsersByMemberUsers(memberUsers);
쿼리는 SELECT  user FROM USER user WHERE user.id = (SELECT member.user_id FROM Member member WHERE member.room_id = :roomId) 로 하면 될 거 같은데 어떻게 적용을 해야할지 모르겠습니다...

2021-07-12 11:59 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +        List<User> users = getUsersByMemberUsers(memberUsers);
```sql
SELECT u 
FROM USER u 
LEFT JOIN Member m
ON u.user.id=m.user_id
WHERE m.room_id=:roomId
```
이렇게 한 다음 User 클래스로 받으면 안 받아지는거야??

2021-07-12 12:01 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +        List<User> users = getUsersByMemberUsers(memberUsers);
JPA 쿼리 결과 인터페이스로 추출하기
- https://www.baeldung.com/jpa-queries-custom-result-with-aggregation-functions

2021-07-12 21:35 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/repository/MemberRepository.java
> +    List<User> findAllMemberUsersByRoomId(@Param("roomId") Long roomId);
수정하면서 오류 관련해서 찾아보니까
예전에는
SELECT *
FROM Member
WHERE room_id = :roomId
이런식으로 db에 있는 이름으로 했는데 객체를 쓰는 방식으로하면 변경한거처럼 코드에서 사용한 이름이랑 객체를 이용하는 식이었네요.
그래서 이전에는 user_id로 하면 Long 값이었는데 m.user로 받으니까 유저로 건너받고 테스트도 잘 동작합니다.

2021-07-13 13:20 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +                .roomAlias(makeInvitedMemberName(users))
이 부분은 기존에 멤버 이름 조합하는 메소드를 조금 변형해서 공유할 수 있도록 만들어도 되지 않을까?

2021-07-13 20:10 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +                .roomAlias(makeInvitedMemberName(users))
초대할때는 초대하는 유저 개체를 가져올려면 추가로 저장소에서 조회를 해야될거 같아서 기존에 채팅방 이름을 만들때 User 객체를 주는 거에서 초대 시 매개변수로 받는 targetUserId를 이용하도록 userId를 받도록 수정해서 하나의 메소드로 처리하도록 했습니다.

2021-07-13 20:54 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +                .roomAlias(makeInvitedMemberName(users))
메소드명을 makeDefaultMemberName으로 지정한 이유는 뭐야?

2021-07-14 14:42 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/service/RoomService.java
> +                .roomAlias(makeInvitedMemberName(users))
원래가 makeJoinMemberNameWithoutUser였는데 Invite할때도 사용하니까 Join은 빼고, makeMemberNameWithoutUser인데 초대할때는 User 리스트에 초대하는 User가 없어서 뭔가 이상한거 같아서 그부분도 뺀 다음에 기본 이름형식이니까 makeDefaultMemberName으로 지정했어요...

2021-07-14 15:11 UTC, woojae9488 approved these changes

2021-07-14 17:25 UTC, merged