Featuring/friend service
LeeHyunSeong/chatting_Jpa pull request #3
Opened 2021-04-29 09:26 UTC by LeeHyunSeong

- Friend 관계 수정 기능 추가 => 친구 관계 기본, 중요, 숨김, 차단으로 수정 가능
- userId를 통해 유저별 전체 친구 목록 조회 기능 추가 => 친구 목록을 위해
- userId를 통해 유저별 숨김 친구 목록 조회 기능 추가 => 숨긴 친구 목록을 위해
- userId를 통해 유저별 차단 친구 목록 조회 기능 추가 => 차단 친구 목록을 위해

2021-04-30 22:49 UTC, woojae9488 requested changes
Comment

2021-04-30 22:49 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/FriendApiController.java
> +    }
대부분 List로 응답값을 내릴 때는 혹시 모를 메타 정보가 추가될 수 있으니 객체를 만들어서 내려주는 걸 추천
예시)
```java
@Getter
@Builder
@ToString
public class GetAllFriendsResponse {
    private List<Friend> friends;
}
```

2021-04-30 22:49 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/FriendApiController.java
> +    }
hide, block 이런 것들은 친구들의 "상태" 값이므로 별도의 메소드를 통해 분리하는 것보다는 getAllFriends에 하나의 파라미터로 친구 타입을 받아서 처리하는 게 더 좋을 거 같다.
`@RequestParam FriendRelationType relationType`

2021-04-30 22:49 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/exception/ControllerAdvice.java
> +    }
이렇게 모든 Exception에 예외핸들러 다는 것보다는 슈퍼 예외 클래스(예를 들어 NotFoundException 정의)를 하나 만들어서 잡거나 RuntimeException으로 잡는게 더 낫지 않나??
위에 NotExistUserException 처리랑 다른 게 없는 거 같아서

2021-04-30 22:49 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/FriendApiController.java
> +    }
Http PUT Method = 데이터 전체 변경
Http PATCH Method = 데이터 일부 변경

2021-04-30 22:49 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/repository/FriendRepository.java
> +    List<Friend> findAllByUserIdAndFriendRelationType(Long userId, FriendRelationType type);
userId, type에 인덱스 걸어야할 거 같은데

2021-05-06 23:53 UTC, woojae9488 requested changes
🔄

2021-05-06 23:53 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/exception/NotFoundException.java
> +}
이런 식으로 만들면 객체지향 설계의 장점을 못 살리는 거 같은데??
String으로 타입을 출력하게 되면 오타가 생길 수도 있고(컴파일 타임 에러 체크 불가), 에러 throw 시마다 타입을 항상 새로 적어줘야하는 거잖아
내가 저번 코멘트에 했던 말은 NotFoundException을 하나 정의를 하고
그걸 상속한 UserNotFoundException, FriendNotFoundException으로 클래스를 설계해서 사용하라는 말이였어

2021-05-06 23:53 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/exception/NotFoundException.java
> +}
어짜피 ExceptionHandler에서는 상속받은 클래스로 잡힐테니까

2021-05-06 23:53 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/model/entity/Friend.java
> +       indexes = @Index(name = "i_friend", unique = true, columnList = "id, relation_type"))
id, relation_type을 인덱스로 잡으면 인덱스를 잡을 필요가 없어진 거 같은데??
id는 private Key로 인덱스가 이미 잡혀있을 거고, id는 모든 row마다 유니크한 값인데 
id, relation_type을 인덱스로 잡으면 쿼리 시 해당 인덱스에 효과가 아예 없는 거 아닌가?
user_id, relation_type을 인덱스로 잡아야 특정 유저의 특정 친구들을 뽑을 수 있을 거 같은데...
그리고 인덱스의 이름은 idx_{col1}_{col1} 이런 식으로 컨벤션을 잡자

2021-05-06 23:53 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/exception/NotFoundException.java
> +}
그리고 NotFoundException은 HttpStatus를 받을 필요가 없이 무조건 HttpStatus.NOT_FOUND일 거 같다

2021-05-06 23:53 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/FriendApiController.java
> +    }
@RequestParam의 경우에는 별도로 value값을 주지 않으면 변수명으로 value를 받는 걸로 알고 있어서 어노테이션의 value값은 지워도 될 거 같고, 내가 봤을 때 기본으로 이 메소드를 호출할 때는 거의 NORMAL 타입으로 호출할 거 같아서 defaultValue를 FriendRelationType.NORMAL으로 줘도 될 거 같은데

2021-05-08 08:03 UTC, woojae9488 approved these changes
re

2021-05-08 08:03 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/controller/FriendApiController.java
> +    public ResponseEntity<String> getAllFriends(@RequestParam Long userId, @RequestParam(required=false, defaultValue="FriendRelationType.NORMAL") FriendRelationType relationType){
이렇게 하면 안될 거 같은데... `defaultValue=FriendRelationType.NORMAL` 이렇게 줘야하는 거 아니야??
""로 묶으면 그냥 문자열이 들어갈 거 같은데??
테스트를 해보고 리뷰 요청한거지..?

2021-05-08 08:03 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/exception/NotFoundException.java
> +        this.status = HttpStatus.NOT_FOUND;
파라미터가 EntityType과 Long id라면 모든 엔티티들의 id 필드 값을 Long으로 지정하려고 하는거지??
만약 다른 타입의 id를 설정할 일이 있으면 어떻게 할거야??
내 생각에는 이렇게 할거면 Object id로 받고 출력을 `String.valueOf(id)`로 넣는게 훨씬 유연할 거 같은데

2021-05-08 08:03 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/exception/NotFoundException.java
> +        this.status = HttpStatus.NOT_FOUND;
아니면 다음과 같이 설계하고 하위 클래스에서 상황에 맞게 구현하는게 맞는 거 같다.
```
 public NotFoundException(EntityType type, String paramsMsg) {
        super(String.format("Can not fount %s entity (%s)", type, paramsMsg));
        this.status = HttpStatus.NOT_FOUND;
}
```

2021-05-08 08:03 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/exception/NotFoundException.java
>      }
이메일은 유저 엔티티 NotFound시에만 사용하는 특이 케이스인데 NotFoundException이라는 슈퍼 클래스에서 정의하는 건 이상하다고 봐

2021-05-08 08:03 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/model/entity/Friend.java
> +       indexes = @Index(name = "idx_userId_relationType", unique = true, columnList = "user_id, relation_type"))
`idx_userId_relationType`이라고 쓰면 camel 케이스와 snake 케이스를 혼용하는 거 같은데... 처음 보는 작명 표기법이네
camel, snake 둘 중 하나만 하자.
여기서는 db 관련이니까 snake 쓰는 게 더 낫겠지.

2021-05-08 08:03 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/exception/NotFoundException.java
> +        this.status = HttpStatus.NOT_FOUND;
그리고 아래 EntityType 보고 생각난 건데, Entity를 추가할때마다 EntityType을 추가하는 건 굉장히 비효율적이고 실수를 유발할 수 있는 코드라고 생각해.
너가 아니라 다른 사람이 여기에 새로운 Entity를 추가하고 NotFoundException을 넣고 싶다고 하면 EntityType을 추가해야 한다는 사실을 깨닫기 어려울 수도 있어
따라서 내 생각에는 EntityType을 이용해 클래스를 구분하는 것보다는 그냥 Class 타입을 인자로 주는게 나을 거 같다.

2021-05-08 08:04 UTC, woojae9488 requested changes
re

2021-05-08 13:05 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/model/entity/Friend.java
> +    private FriendRelationType friendRelationType;
여기 변수명은 왜 수정한거야??

2021-05-08 13:06 UTC, woojae9488 commented on src/main/java/com/lhs/chatting/exception/NotFoundException.java
>      }
음.. 내가 말한 건 Object type으로 받는 걸 말하는 게 아니라 Class<T> clazz로 받는 걸 말하는 거였어

2021-05-08 18:46 UTC, LeeHyunSeong commented on src/main/java/com/lhs/chatting/model/entity/Friend.java
> +    private FriendRelationType friendRelationType;
![image](https://user-images.githubusercontent.com/61196115/117550060-0a94fe00-b079-11eb-9d22-272678b05462.png)
FriendRelationType 형에 매치를 못시키는 거 같아서 변수명을 저렇게 수정하니까 위에 오류 사라지더라고요. 그래서 수정했어요

2021-05-11 22:54 UTC, woojae9488 approved these changes

2021-05-12 07:32 UTC, merged